### ISSUE TITLE
Flutter integration 

### ISSUE THREAD

**Issue by SehribanTas** [google-home/sample-app-for-matter-android#101]
Is there a way to use matter with flutter?

**Comment by pierredelisle** [comment]
This question would be better directed to a flutter group (e.g. https://stackoverflow.com/questions/tagged/flutter).
From my limited knowledge, Flutter does support writing platform specific code. I believe "platform" channels is what's allows this:
"A platform channel is a flexible messaging API between a Flutter app and the platform hosting the app. It's how you can communicate with native and 3rd-party APIs."
But again, better ask the Flutter experts about this.
