### ISSUE TITLE
en pressing the add button does not do anything 

### ISSUE THREAD

**Issue by NovakiDouglas** [google-home/sample-app-for-matter-android#103]
when pressing the add button does not do anything and I get the following error
com.google.android.gms.common.api.ApiException: 17: API: CommissioningClient.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}

[logs.txt](https://github.com/google-home/sample-app-for-matter-android/files/10980858/logs.txt)

**Comment by pierredelisle** [comment]
This is a dUplicate of https://github.com/google-home/sample-app-for-matter-android/issues/70. Please see details and workaround there.
