### ISSUE TITLE
Generate next device ID

### ISSUE THREAD

**Issue by edWin-m** [google-home/sample-app-for-matter-android#113]
@pierredelisle When commissioning a device, we first generate a device identifier by incrementing a counter. 
https://github.com/google-home/sample-app-for-matter-android/blob/906db51258c3cfec9608c1b647ec3fc598c3bcfe/app/src/main/java/com/google/homesampleapp/commissioning/AppCommissioningService.kt#L98

Is it possible to use the compressed fabric Id to query all the devices in the fabric?  This way, we can calculate the next available device Id based on the returned devices.

**Comment by pierredelisle** [comment]
@edWin-m Edwin, yes, we could definitely do that, but to be honest, it'd probably be better to use a random id.
Are you running into an issue because the "remove device" is not fully implemented in the sample app? That is, while we remove the device from internal storage, we do not currently send a command to the device to remove it from our fabric. 
[BTW, I should have a PR out soon to properly do the fabric removal at the device].

**Comment by edWin-m** [comment]
@pierredelisle noted, how would one go about that?  I have scoured the methods provided in the `ChipDeviceController`, but I can't find any method related to this.

https://github.com/google-home/sample-app-for-matter-android/blob/906db51258c3cfec9608c1b647ec3fc598c3bcfe/app/src/main/java/com/google/homesampleapp/chip/ChipClient.kt#L50

I would like to try both methods and weigh the pros and cons afterward.  As for removing devices from the fabric, I already have that covered.

**Comment by pierredelisle** [comment]
> As for removing devices from the fabric, I already have that covered.

Edwin, how about a little PR so we can get that merged into main? 
Trying to encourage community contributions :-) We just had our first one with https://github.com/google-home/sample-app-for-matter-android/pull/115.

**Comment by edWin-m** [comment]
> > As for removing devices from the fabric, I already have that covered.
> 
> Edwin, how about a little PR so we can get that merged into main? Trying to encourage community contributions :-) We just had our first one with #115.

@pierredelisle  Sure thing. Any luck with querying the devices sharing a fabric with the app?

**Comment by pierredelisle** [comment]
Tagged with "enhancement". Contributions always welcome.
