### ISSUE TITLE
End device(Light) is not shown on mobile application

### ISSUE THREAD

**Issue by palak-android** [google-home/sample-app-for-matter-android#114]
End device(Light) is not shown on mobile application after successful pairing when user touch/click anywhere instead of device name text box.

**Description:** During the testing, we observed that whenever the user added a new device after pairing and touched/click anywhere in the mobile app screen instead of the Text box of the device name. the newly paired device is not shown on the mobile application.

**Note:**
- This issue is reproducible multiple times (approx. 10 times out of 10 attempts) during testing.
- This issue is not specific to any mobile device and reproducible for all android mobiles.

**PREREQUISITES:**
1. End device EFR32MG24 (Light Device) is available and in reset mode.
2. Wi-Fi chip (Rs9116) is available to make Wi-Fi support.
3. Android Mobile device with Google home Mobile App.
4. Mobile Bluetooth, Wi-Fi & Location is enabled and on the same Wi-Fi network.
5. End device EFR32MG24 (Light device) and both android mobile are on the same Wi-Fi network.

**STEPS:**
1. Check HW is Ready and up to date for commissioning.
2. Press '+' button on mobile application and check behavior
3. Press Set up without the QR code
4. enter the pairing code/ Scan the QR code and press next.
5. after successful pairing touch / Click anywhere instead of the TEXT BOX of the device name.
6. Check the behavior of the Mobile application

**EXPECTED RESULT:**
- In the Mobile application Device name TEXT BOX should not be removed or redirected without a name.

**ACTUAL RESULT:**
1. Text Box vanished, and End Device is not able to find in the mobile application.

**Test Setup:**
- End device EFR32MG24 (Light Device)
- Wi-Fi chip (Rs9116)

**Mobile Device:** Any Mobile (Moto 20 Fusion Plus, Samsung M31)
**Mobile Android version:** v13 or more
**Mobile App:** Google Home Sample Application For Matter ( GHSAFM )
**Mobile App Release:** v1.4.1

Please find attached video for the same.
https://user-images.githubusercontent.com/38459626/230608018-1cd249a9-15ce-4eeb-b42a-ebe62b6ca95c.mp4

Thank you,
Palak Suhagia

**Comment by pierredelisle** [comment]
Thanks for filing this issue and the associated PR. Much appreciated! Verified the fix in #115. We'll just need you to complete the CLA and the PR can be merged.
