### ISSUE TITLE
AndroidManifest.xml error: com.google.android.gms.metadata.ModuleDependencies, was not found in the project or the libraries

### ISSUE THREAD

**Issue by karlingen** [google-home/sample-app-for-matter-android#117]
I'm seeing the error below due to this code in AndroidManifest.xml: 

```xml
<service android:name="com.google.android.gms.metadata.ModuleDependencies"
    android:enabled="false"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.android.gms.metadata.MODULE_DEPENDENCIES" />
    </intent-filter>

    <meta-data android:name="home:0:preferred" android:value=""/>
</service>
```

**Error:** 
> Class referenced in the manifest, com.google.android.gms.metadata.ModuleDependencies, was not found in the project or the libraries
Unresolved class 'ModuleDependencies'

![image](https://user-images.githubusercontent.com/2265452/231281711-0b21bc8c-2e1b-4030-bfc1-a835e07e0728.png)

Do we need to import a library in the build.gradle file? If so, which one?

**Comment by pierredelisle** [comment]
Does that prevent you from building the project?
I also see that error, but has no impact to successfully build the project in Android Studio.

**Comment by karlingen** [comment]
The project builds successfully. But I'm curious what would happen if this app was deployed to a device running Android less than 11 - whether the backported photo picker would get installed on the device or not. 

I assume that was [the reason](https://developer.android.com/training/data-storage/shared/photopicker#device-availability) why this service was added to the AndroidManifest.xml file.

**Comment by pierredelisle** [comment]
I don't think there is anything pending that's specific to the sample app. Closing for now.
