### ISSUE TITLE
Matter Sdk version

### ISSUE THREAD

**Issue by LisaR-w** [google-home/sample-app-for-matter-android#127]
Hello,

I'm currently mentioned that the Matter sdk version, which is used here (since 1.4.0), is an Release Candidate and also the last versions of the Matter sdk were commits and not versions of the matter sdk that are tagged as release.

Is there any documentation, why these versions are used and is there any roadmap, when the sample app depends on a "release version" of the matter sdk?

If not are there any reasons for using the candidates or commits without tagging, although they are not released?

Thanks in advance for the answers

**Comment by pierredelisle** [comment]
Hi,

As you noted, we last updated the Matter SDK with [v1.4.0](https://github.com/google-home/sample-app-for-matter-android/releases/tag/v1.4.0) with TE_23_02/rc2.

We try to update the Matter SDK used in the sample app whenever a key tagged release is available at the connectedhome GitHub repo. Looks like we could upgrade to SVE_23_03/rc2.

So we can prioritize this update, could you provide more information why using the latest key tagged release of the Matter SDK is important to you currently?

**Comment by LisaR-w** [comment]
Hi,

i thought that this versions where release candidates and not completely released versions. However if they are my question was answered completely :) 

For me, updating has no increased priority.

Thanks for the fast answer, the issue can be closed
