### ISSUE TITLE
Connectivity problem when commissioning

### ISSUE THREAD

**Issue by Diegorro98** [google-home/sample-app-for-matter-android#13]
I can't perform commissioning process to connect an [esp32 light example](https://github.com/espressif/esp-matter/tree/main/examples/light) from the [esp-matter repo](https://github.com/espressif/esp-matter) although that with other tools, such as HomeAssistant or Chip-tool, I'm able to perform the process and interact with the device.
I can start the commissioning process, and watching the logs from the esp32, the phone and the esp32 seems to be communicating with each other, but at the end, at the phone I get "Connectivity problem. We're having trouble communicating with Google." message and there is no added device after all.

I already send a report through the feedback option from the three dots menu over the error explaining exactly the same.

**Comment by screensforme** [comment]
Even I am facing the same issue.. I am using the Google home sample app from https://developers.home.google.com/matter.  Is there any pre-requisite to be done ?

**Comment by Vyrastas** [comment]
Can you try the solution suggested in #11 ?

**Comment by Diegorro98** [comment]
I'm sorry that this issue is a duplicate, that was the problem, although now I'm facing another issue, but I will close this one and open another one about that later with some logs.
