### ISSUE TITLE
Pictures for devices in Google Matter console

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#135]
How can I retrieve the device pictures you upload to the Google Matter console?

**Comment by jonsmirl** [comment]
Go into the Google Matter console...
https://console.home.google.com/projects

Now add a new device. On the second dialog page for creating the device you can upload custom pictures.
--
How does an app access them?

**Comment by pierredelisle** [comment]
Got it. These pictures will only be accessible to the Google Home Application.
