### ISSUE TITLE
question about commission environment

### ISSUE THREAD

**Issue by jungwook-park** [google-home/sample-app-for-matter-android#14]
Hi All
I have a question
I tried to set a commission with Pixel & Google Nest 2gen & SiliconLabs(BRD4161A) 
but commissioning is failed.
I captured the failed log attaching the file
Can I get the advice for solving this problem??

[HomeConnectionLog.txt](https://github.com/google-home/sample-app-for-matter-android/files/9652004/HomeConnectionLog.txt)

**Comment by aBozowski** [comment]
Can you please confirm the commit (`git show`) and path (e.g. `/examples/lighting-app/efr32/`) of the example used?

The currently supported source is documented [here](https://developers.home.google.com/matter/vendors/silicon-labs#initial_setup). Please note that this is subject to change.

**Comment by pierredelisle** [comment]
Closing this issue for now as no additional information from OP.
