### ISSUE TITLE
Regulatory region for wifi

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#145]
Can you explain this to them...
https://issuetracker.google.com/issues/283470659

The GPS library should be setting the regulatory region, not everyone's app. When GPS sets in the wifi credentials it should follow up by also setting the regulatory region.

**Comment by pierredelisle** [comment]
See https://issuetracker.google.com/issues/283470659 for details, as well as https://github.com/project-chip/connectedhomeip/issues/27445.
