### ISSUE TITLE
Matter sample app stopped working

### ISSUE THREAD

**Issue by khushbushah2302** [google-home/sample-app-for-matter-android#147]
Hi,

I was using this app to commission matter device. It was working fine. 
Suddenly from last few days it stopped working. I've also tried adding the device through the Google Home app and it works. 
But not able to commission device using this sample app.

Here are the device logs :
[Device_logs.txt](https://github.com/google-home/sample-app-for-matter-android/files/11878850/Device_logs.txt)

**Comment by pierredelisle** [comment]
Looking at the device logs, it is not clear what the sequence of events was, but looks like the device was commissioned first, and then multi-admin attempted?

```
...
I (87257) chip[SVR]: Commissioning completed successfully
...
I (88647) chip[ZCL]: Commissioning window is now open
...
I (93137) chip[ZCL]: OpCreds: AttestationRequest successful.
...
I (94197) chip[ZCL]: OpCreds: AllocatePendingOperationalKey succeeded
I (94457) chip[ZCL]: OpCreds: CSRRequest successful.
I (94457) chip[EM]: <<< [E:4725r S:1639 M:47687077 (Ack:60898645)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (94477) chip[IN]: (S) Sending msg 47687077 on secure session with LSID: 1639
E (94477) chip[DL]: Long dispatch time: 830 ms, for event type 3
I (94817) chip[IN]: (S) Sending msg 47687077 on secure session with LSID: 1639
I (95147) chip[IN]: (S) Sending msg 47687077 on secure session with LSID: 1639
I (95747) chip[IN]: (S) Sending msg 47687077 on secure session with LSID: 1639
I (96697) chip[IN]: (S) Sending msg 47687077 on secure session with LSID: 1639
E (98137) chip[EM]: Failed to Send CHIP MessageCounter:47687077 on exchange 4725r sendCount: 4 max retries: 4
I (153357) chip[FS]: Fail-safe timer expired
E (153357) chip[SVR]: Failsafe timer expired
I (153367) chip[SC]: SecureSession[0x3ffc8970]: Moving from state 'kActive' --> 'kPendingEviction'
E (153377) chip[SVR]: Commissioning failed (attempt 1): 32
```

Please follow the instructions at https://github.com/google-home/sample-app-for-matter-android/wiki/How-to-investigate-issues-with-the-sample-app-(GHSAFM) to provide complete information and help investigate possible issues.

**Comment by khushbushah2302** [comment]
Working fine now. Closing this issue.

**Comment by khushbushah2302** [comment]
Working fine now. Closing this issue.
