### ISSUE TITLE
Custom commissioning UI | Get SSID and Password  

### ISSUE THREAD

**Issue by mukesh-simform** [google-home/sample-app-for-matter-android#150]
Here sample app manages the entire commissioning flow but as per our requirement we want to implement custom commissioning flows instead of using **System UI** is there any possibility of using [Home APIs](https://developers.home.google.com/reference/com/google/android/gms/home/matter/package-summary) with `custom UI` instead of Play Services provided default UI (Scanner / Managing network credential internally) or it will commission through Google Play Services and Default UI only?

As of now, we're following [CHIPTool](https://github.com/project-chip/connectedhomeip/tree/master/examples/android/CHIPTool) And the user has to provide SSID and Password as input in the commissioning flow. But we want to automate that so that users don't have to enter any network credentials manually 

How can I get SSID / Password automatically, Is it something possible in Android at all to get current network credentials to automate this process even in custom commissioning flows?

**Comment by pierredelisle** [comment]
A key goal of the Google Home Mobile SDK is so that you don't have to deal with these issues. So, no, it's not possible to cherry-pick specific functionality from it.
