### ISSUE TITLE
Why is sample polling instead of using a notification?

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#33]
Wouldn't it be more responsive if the app subscribed to notifications from the devices instead of polling them?

**Comment by pierredelisle** [comment]
Totally agree. When the app was first written, there were issues with notifications. On the TODO list.

**Comment by pierredelisle** [comment]
See PR #66. https://github.com/google-home/sample-app-for-matter-android/pull/66.

**Comment by pierredelisle** [comment]
PR #66 has now ben merged.
