### ISSUE TITLE
Allowing uncertified devices

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#34]
When I add an uncertified device to Apple Home during commissioning I get a popup asking me if I want to allow the uncertified device onto the Matter network. So how do you implement this popup on the Google side?

**Comment by pierredelisle** [comment]
There's an ongoing discussion on that topic. We should hopefully have more details soon'ish.

**Comment by pierredelisle** [comment]
PR #92 bypasses a device certification failure.
Agree that ideally a dialog should be shown asking the user whether the failure should be ignored or not.
Problem is that currently this happens while the UI is controlled by GPS, and showing such a dialog is not supported. Feature request has been filed.
