### ISSUE TITLE
Fields in Basic Info cluster

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#35]
In devices.proto you have vendorId and productId as strings, but they are Uints in Matter. Also, I find it more useful to display the name and vendor strings than the ids, so I changed it like this:

    // VID / PID
    uint32 vendorId = 2;
    string vendorName =3;
    uint32 productId = 4;
    string productName = 5;

Over in ClusterHelpers readBasicClusterVendorIDAttribute() is not useful or used because the commissioning API returns the vendorId. So I deleted it and added readBasicClusterVendorNameAttribute() and readBasicClusterProductNameAttribute()

I have not checked this yet, but when you assign the device name in the Google Home dialog it should also write that name into the BasicInfo cluster using the NodeLabel Attribute, then the sample app can retrieve that string and use the same device name that the Home app is using.

```
NodeLabel Attribute
The NodeLabel attribute SHALL represent a user defined name for the Node. This attribute
SHOULD be set during initial commissioning and MAY be updated by further reconfigurations.
```

I also removed the endpoint parameter from these calls since it is only legal to have the Basic Info cluster on EP0.

**Comment by jonsmirl** [comment]
Google Home is setting the name into NodeLabel.  So I read it out of the device and then use it in the Name field of Device.
```
         val nodeLabel = clustersHelper.readBasicClusterNodeLabelAttribute(deviceId)

            devicesRepository.addDevice(
                Device.newBuilder()
                    .setName(nodeLabel) // default name that can be overridden by user in next step
                    .setDeviceId(deviceId)
```

**Comment by pierredelisle** [comment]
Thanks for these comments. I'll be looking will look into integrating them in the codebase.
