### ISSUE TITLE
Room for device

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#40]
Is there any mechanism to keep the room label for a device synchronized between Google Home and GHSAFM?

This should have been an attribute on the Basic Information cluster but it is not there. As a work around it could be encoded into NodeLabel, but then Google/Apple/Amazon need to agree on how it is encoded.

**Comment by jonsmirl** [comment]
I don't believe result.room can ever be set since Google Home does not allow room assignment until after a device is commissioned.
```
                val result =
                    CommissioningResult.fromIntentSenderResult(activityResult.resultCode, activityResult.data)
                val roomName =
                    result.room?.name // needed 'cause smartcast impossible with open/custom getter
                if (roomName != null) updatedDeviceBuilder.room = roomName
                devicesRepository.updateDevice(updatedDeviceBuilder.build())
```

**Comment by pierredelisle** [comment]
Agree that it's currently an issue.
Note that there are some ongoing discussions regarding this very topic. Not clear yet what the final outcome will be once the Google Home Matter API is officially released.   (remember that is is a "developer preview" and things may/will change).

**Comment by pierredelisle** [comment]
The Commissioning API was modified to commission to a Local Android fabric instead of the Google Home fabric. This issue does not apply anymore as the local android fabric does not have any notion of structure nor room.
