### ISSUE TITLE
Documentation for the CHIP jars

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#41]
I can't find documentation for any of the CHIP API at developers.home.google.com, shouldn't it be listed here?
https://developers.home.google.com/reference/com/google/android/gms/home/matter/commissioning/package-summary

The API all appears to be there, but many of the necessary parameters are completely mysterious and undocumented.

**Comment by pierredelisle** [comment]
Could you clarify what you mean by the CHIP API?
What's documented at https://developers.home.google.com/reference/com/google/android/gms/home/matter/commissioning/package-summary is the "Google Home Matter APIs". 

The Matter SDK that we include with the sample app (under third_party/connectedhomeip) comes straight from the connectedhomeip github repo and documentation of these APIs should hopefully be provided there eventually.

**Comment by jonsmirl** [comment]
There is no doc at connectedhomeip github for the Matter SDK, I am figuring this stuff out by reading the source code.  Any idea when a real doc team is going to document these APIs?

**Comment by pierredelisle** [comment]
I'd suggest filing an issue with that very question at the connectedhomeip github repo.
