### ISSUE TITLE
How to create Groups and Bindings from ChipDeviceController

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#42]
How do I translate these into API calls on the CHIP controller?
```
./chip-tool groupsettings add-group grp1 0x0001
./chip-tool groupsettings add-keysets 0x0042 0 0x000000000021dfe0 hex:d0d1d2d3d4d5d6d7d8d9dadbdcdddedf
./chip-tool groupsettings bind-keyset 0x0001 0x0042
```

**Comment by jonsmirl** [comment]
This is how you do it for a device,   ChipClusters.GroupsCluster(devicePtr, endpoint).addGroup(), what do I put in for devicePtr and endpoint to do it on the Controller?

**Comment by pierredelisle** [comment]
I assume you refer to https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/CHIPDeviceController-JNI.cpp?

This is code that's from the connectedhomeip github repo. These kind of questions should be directed there.

**Comment by jonsmirl** [comment]
I'll file it with the 9,000 other unaddressed issues there.

Maybe I can read the old source code for Android CHIPTool and figure it out.
