### ISSUE TITLE
Dynamic parts list on EP0

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#43]
Section 9.13.6 of the CHIP spec describes how a controller is able to monitor devices being added or removed from a bridge.
```
When an update to the set of Bridged Devices (which are exposed according to the Section 9.13.11,
“Best practices for Bridge Manufacturers”) occurs, the Bridge SHALL
• on the Descriptor cluster of endpoint 0: update the PartsList attribute (add/remove entries from
this list)
• update the exposed endpoints and their descriptors according to the new set of Bridged Devices

Nodes that wish to be notified of added/removed devices SHOULD monitor changes of the PartsList
attribute in the Descriptor cluster on endpoint 0.
```

Does Google Home monitor EP0/PartsList on every device, or does it look for Bridges and only monitor EP0/PartsList on those devices?

If I have a non-bridge device, dynamically create an EP (which is not disallowed) and update EP0/PartsList will Google Home rescan the device and add/remove an icon for the new EP?  Or do I need to create a bogus bridge cluster (aggregator)?

**Comment by mspang** [comment]
If an endpoint is added or removed, the devices are updated _as if_ the device had been initially commissioned in that state. This applies to bridges and non-bridges.
