### ISSUE TITLE
Commissioning API needs to return FabricId

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#44]
The commissioning API does not return the FabricId (or I can't find it) for the newly commissioned device. This needs to saved with the device ID because later you have to have FabricId in order to be able to set the ACL. FabricId can vary by the device since it is a function of how many times the device has been commissioned.  

I am trying to work around this by reading the ACL list back out of the device and searching it for my commissioning ACL entry which contains the FabricId.

**Comment by pierredelisle** [comment]
When you say the "commissioning API", which API are you referring to?
The sample app depends on the Matter SDK and that would be the API provided by [CHIPDeviceController](https://github.com/project-chip/connectedhomeip/blob/master/src/controller/CHIPDeviceController.cpp), correct?

I haven't spent much time digging into the internals of that class, but if you have specific suggestions on how that API should be modified/improved, I can help lobby for these changes.

**Comment by jonsmirl** [comment]
CommissioningResult.fromIntentSenderResult(activityResult.resultCode, activityResult.data)  should also return the fabric ID assigned. It is printed out in the CHIP logs, it just needs to be added the returned structure.

Many people are ignoring this right now since they are only using a single fabric and it always get assign to ID #1.  Once you start having more commissioners they will be ID 2,3,4, etc per device.  Also you can have slots taken up stale commissions.  The ID assigned is a function of how many time the device has been commissioned.  So Google might be assuming slot 1, but if someone commissions the device onto Apple first and then Google, Google is going to get slot 2.  These slot assignments vary by the order in which the device has been commissioned in, so you need to save it with the deviceId. They also vary by device.

The FabricId is a parameter to the ACL calls, so you need it later.

**Comment by jonsmirl** [comment]
Core Matter has been fixed to not require this anymore.
