### ISSUE TITLE
How can I check that the matter feature of the current phone is available?

### ISSUE THREAD

**Issue by panliming-tuya** [google-home/sample-app-for-matter-android#45]
I see this: https://developers.home.google.com/matter/verify-services

But when users use it, there is difficult to do these operations.

Is there any way to determine that GMS service in the user's mobile phone supports the Matter feature?

**Comment by pierredelisle7** [comment]
Run this command in a terminal to verify that the necessary Matter modules are installed:

```
adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep "com.google.android.gms.home"
```
If you see output similar to the below, you have the Matter modules installed:
```
com.google.android.gms.home [v222110900]
```

**Comment by Vyrastas** [comment]
Specifically covered here too: https://developers.home.google.com/matter/build/troubleshooting#verify_your_gps_matter_modules

We probably should surface that section in the Verify Services page too, though at this point the rollout of modules has long been 100% and any supported Android device ideally should have them by now.

**Comment by yunjedi** [comment]
You can detect user's mobile phone supports the Matter feature programmatically

` Matter.getCommissioningClient(context)
        .commissionDevice(commissionDeviceRequest)
        .addOnSuccessListener { result ->
          Timber.d("ShareDevice: Success getting the IntentSender: result [${result}]")
          // Communication with fragment is via livedata
          _commissionDeviceIntentSender.postValue(result)
        }
        .addOnFailureListener { error ->
          Timber.e(error)
          _commissionDeviceStatus.postValue(
              TaskStatus.Failed("Setting up the IntentSender failed", error))
        }`
if error is ApiException, I assump user's mobile phone unsupports the Matter
