### ISSUE TITLE
Cannot use sample app to install matter device running on ESP32

### ISSUE THREAD

**Issue by matdev** [google-home/sample-app-for-matter-android#54]
I've two Matter wifi devices running on ESP32 devkits (C3 and S3) and a Google Nest.

I can install and control both of them nicely using Google Home app.

But I cannot install them using the default sample app for matter, neither using the targetcommissioner variant.

Can you please let me know what to do ?
Where should I put a breakpoint to check whether the device is scanned by the app ?

**Comment by pierredelisle** [comment]
Best would be to start from scratch and provide logs to figure out what is going on.

- Reset the device under test (so it goes back to a commissionable state)
- Reset the sample app 
  - App Info > Storage & cache > Clear storage
- Clear the logs of the phone
   - adb logcat -c
- Start capturing the logs of the phone
   - adb logcat > logs.txt

On your phone, start the sample app and click on "+" to commission the device.

Once processing is complete (e.g. it fails commissioning), kill the "adb logcat" command above, and attach the logs file to this issue.

**Comment by matdev** [comment]
Ok. Here is the logs file:
[logs.txt](https://github.com/google-home/sample-app-for-matter-android/files/10235921/logs.txt)

**Comment by matdev** [comment]
Actually after a proper reset I was able to commission the device and control it from the sample app !
It took about 1 minute to complete, is it normal ?

Also, do you know if it's possible to commission a device that's already installed in Google Home app ?
i.e. can we query Google Nest for already installed Matter devices and install them in sample app ?

**Comment by pierredelisle** [comment]
> It took about 1 minute to complete, is it normal ?

Yes, it should eventually be faster than that, but for now this could be expected.

> Also, is it possible to install a device that's already commissioned with Google Home app ?

Yes. For that you have to use the "multi-admin" feature.

Settings > Google > Devices & sharing > Matter devices
Tap on the device 
Tap on "Linked Matter apps & services"
Tap on "Link apps & services"
Tap on the sample app (GHSAFM) to trigger multi-admin to the sample app

**Comment by pierredelisle** [comment]
Looks like this is being blocked by https://github.com/google-home/sample-app-for-matter-android/issues/60, which is being investigated.

**Comment by pierredelisle** [comment]
I believe this is related to https://github.com/google-home/sample-app-for-matter-android/issues/61 which has been fixed.
