### ISSUE TITLE
Unable to see Matter devices & services option on Pixel 4a (Android 13)

### ISSUE THREAD

**Issue by matdev** [google-home/sample-app-for-matter-android#60]
I've followed the procedure described here:
https://developers.home.google.com/matter/verify-services

Basically I upgraded Google Services to the latest version and re-installed Google Home App.

Despite that, I don't see the 
**Matter devices & services** option in **Settings > Google > Devices & sharing**

Any idea what to do please ?

**Comment by pierredelisle** [comment]
Thanks for reporting this issue. Investigating...

**Comment by pierredelisle** [comment]
Hmm, we had a few other reports of this issue, and re-installing the Google Home App solved the issue.
Which version of GHA is currently running on your phone?

**Comment by matdev** [comment]
My phone is running version 2.62.60.2 of GHA
Indeed, after uninstalling GHA and re-installing it, the **Matter devices** option appears in Settings > Google > Devices & sharing
