### ISSUE TITLE
Implementing commissioning in custom app

### ISSUE THREAD

**Issue by matdev** [google-home/sample-app-for-matter-android#63]
I'm trying to implement the commissioning mecanism in a custom app written in Java.

Here is my version of commissionDevice() in Java:

```
public void commissionDevice() {

        CommissioningRequest commissionDeviceRequest = CommissioningRequest.builder()
                .setCommissioningService(new ComponentName(this, AppCommissioningService.class.getName()))
                .build();
        
        Matter.getCommissioningClient(this)
                .commissionDevice(commissionDeviceRequest)
                .addOnSuccessListener(new OnSuccessListener<IntentSender>() {
                    @Override
                    public void onSuccess(IntentSender intentSender) {
                        Log.i(getClass().getName(), "onSuccess() Success getting the IntentSender");
                        // Communication with fragment is via livedata
                        _commissionDeviceIntentSender.postValue(intentSender);
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.e(getClass().getName(), "onFailure() Setting up the IntentSender failed : " + e.getMessage());
                    }
                });
    }
```

Calling this method properly triggers `onSuccess()` callback, but for some reason the call to `_commissionDeviceIntentSender.postValue(intentSender);` does nothing, and no error log to help.

Shouldn't this call open the "Scan Matter QR code" screen ?

Can you please help getting this working ?

**Comment by pierredelisle** [comment]
> Shouldn't this call open the "Scan Matter QR code" screen ?

All this does is post an event to the live data (commissionDeviceIntentSender), and the Fragment is then responsible to make the call to launch the intent.

I'd suggest looking at this presentation:
https://github.com/google-home/sample-app-for-matter-android/blob/main/docs/GoogleHomeMobileSDK.pdf

Review the slides that talk about the 5 steps to mastering the ActivityResult API.

**Comment by matdev** [comment]
Thanks for links. Using this [doc](https://developers.home.google.com/reference/com/google/android/gms/home/matter/commissioning/CommissioningClient#commissionDevice(com.google.android.gms.home.matter.commissioning.CommissioningRequest)), I'm now able to start the commissionDevice intent from the app in Java.

But for some reason, my `AppCommissioningService's onCommissioningRequested` method is not called.
Any idea why ?
