### ISSUE TITLE
Exception in onCommissioningRequested(): lateinit property chipClient has not been initialized

### ISSUE THREAD

**Issue by matdev** [google-home/sample-app-for-matter-android#65]
I'm trying to implement the commissioning mecanism in a custom app
After starting commissioning a device, the method `AppCommissioningService`'s `onCommissioningRequested()` is properly called, but then the following exception is thrown:

**lateinit property chipClient has not been initialized**

Any idea why ?
How to initialize `chipClient` ?

For info, here is how chipClient is declared in the service:
```
@Inject
internal lateinit var chipClient: ChipClient

```

**Comment by pierredelisle** [comment]
Do you have class ChipClient in your app?
See https://github.com/google-home/sample-app-for-matter-android/blob/main/app/src/main/java/com/google/homesampleapp/chip/ChipClient.kt.

**Comment by matdev** [comment]
Indeed, now I initialize the chipClient using the ChipClient_Factory:
`chipClient = ChipClient_Factory.newInstance(this);`

It seems to work, but then in order to call
```
chipClient.awaitEstablishPaseConnection(deviceId, metadata.getNetworkLocation().getIpAddress().getHostAddress(),
                metadata.getNetworkLocation().getPort(), metadata.getPasscode(), continuation);
```
a Continuation instance is needed. 
Any idea how to initialize it properly in Java ?

**Comment by pierredelisle** [comment]
Sorry, my area of expertise will be limited to the sample app itself and Kotlin. 
But stackoverflow can always be your friend :-)

**Comment by tetedoie** [comment]
It look like a dependency injection issue. Your lateinit variable is not initialized which is strange as it's annotated with `@Inject` so it's supposed to be initialized by Dagger/Hilt. My first guess is that your `AppCommissioningService` class is not annotated with `@AndroidEntryPoint` so the Hilt compiler ignore the class and its fields annotated with `@Inject` aren't actually injected.
