### ISSUE TITLE
My Google Home Display keeps restarting 

### ISSUE THREAD

**Issue by jonsmirl** [google-home/sample-app-for-matter-android#73]
How can I get the logcat from it? Logcat should show me where the problem is.  I'm probably sending it something it doesn't like.

**Comment by aBozowski** [comment]
Hi Jon,

For production builds, hub logs are not locally available. If you're able to catch the issue shortly after it occurs, please send feedback from either the settings menu or by issuing the voice command "send feedback."  When describing the issue, please add some distinguishing detail such as "matter sample app issue 73."

**Comment by jonsmirl** [comment]
Maybe add an option to Hub so that if it is in preview mode you can get the logcat?

I will keep an eye on my hub. The restart is not immediately coupled with whatever I am doing. It is behaving like a memory leak and it takes a while to to eat up all of the memory.  It is definitely coupled to commissioning the new Matter devices I am working on.

**Comment by aBozowski** [comment]
Hi Jon,

Your feedback regarding logs is noted and appreciated.   
Presently, there is only one path forward, so I will close this issue for now.
Please file feedback if the issue occurs again so the appropriate team can investigate.
