### ISSUE TITLE
Commissioning with "Matter Virtual Device"

### ISSUE THREAD

**Issue by TimYao18** [google-home/sample-app-for-matter-android#77]
In [Build a Matter virtual device](https://developers.home.google.com/codelabs/matter-device-virtual) Colab, it teaches us how to make a Matter virtual device. In step [6. Commission the device](https://developers.home.google.com/codelabs/matter-device-virtual#5), it says a hub is required to commission your device on the Matter fabric.
In [Build an Android App for Matter](https://developers.home.google.com/codelabs/matter-sample-app) Colab, it teaches us how to make an Android App that works with a virtual device or an ESP32. In the welcome page, it says "You don't need a hub, for example a Google Nest Hub (2nd Generation), to commission and control devices with the sample app."

When I connect to the Matter virtual device using the Google Home app, the screenshot shows "You need a hub to control with Google." and "Can't find device." I test the commissioning using GHSAFM, and no luck "Can't find device." too. 

Is a Google Nest hub Gen 2 required for commissioning the virtual device? 

---
Matter virtual device environment: Windows 11 Subsystem for Linux, run Docker.
Android device: Sony Xperia 1; OS: Android 11; Google Play services version: 23.03.13 (150400-503260631); Google Home app shows Matter related text and detect the Matter device.

**Comment by pierredelisle** [comment]
You won't be able to control the device via the Google Home App (GHA), but you will be able to control it with the sample app if you commission the device with it.

Please follow instructions at https://github.com/google-home/sample-app-for-matter-android/wiki/How-to-investigate-issues-with-the-sample-app-(GHSAFM) and provide all the information mentioned (more specifically, the phone logs) if you want us to investigate.

**Comment by TimYao18** [comment]
Thank you for your reply. 
After trying, the Matter virtual device  can be commissioned with Sample app directly without a hub. 

I met problem because I use the machine is not a Linux. 
The Matter virtual device run under: Windows subsystem for Linux, Windows with Ubuntu in the VirtualBox, Mac with Ubuntu installed in VirtualBox, won't be commissionable.
