### ISSUE TITLE
Unable to publish to Play Store - GmsCore module dependency minimum version declared in the AndroidManifest.xml file is invalid: -1

### ISSUE THREAD

**Issue by jpelgrom** [google-home/sample-app-for-matter-android#81]
When trying to publish an app to the Play Store containing code based on this example it fails with the following message:

```
"message": "The GmsCore module dependency minimum version declared in the AndroidManifest.xml file is invalid: -1.",
"status": "PERMISSION_DENIED"
```

It appears to refer to this code:

https://github.com/google-home/sample-app-for-matter-android/blob/264c8404cac2b5d1e4195adb6cea4caf12c812bc/app/src/main/AndroidManifest.xml#L71-L79

Is the example incorrect or is using it restricted in some way? It appears to indicate to Play Services to download the Matter modules, which is useful to have in case the user doesn't have them installed (or doesn't want to re-install the Google Home app to trigger a download).

**Comment by pierredelisle** [comment]
Quick update: Issue acknowledged and team is working on a fix.

**Comment by pierredelisle** [comment]
It should be "home:-0:preferred". I'll send a PR shortly to fix.
