### ISSUE TITLE
[native] native crash

### ISSUE THREAD

**Issue by nicelyjust** [google-home/sample-app-for-matter-android#87]
Reproduction steps
1. A test device([tv-app](https://github.com/project-chip/connectedhomeip/tree/master/examples/tv-app)) was commissioned by GHSAFM
2. stay on the homepage for a while,then it may crash

Version(s)
latest

LOG
[crash.txt](https://github.com/google-home/sample-app-for-matter-android/files/10822476/crash.txt)

**Comment by pierredelisle** [comment]
OK, so looks like this may be related to #91.
If someone can provide details on how to reproduce consistently, it will be easier to investigate.

**Comment by pierredelisle** [comment]
Have been able to reproduce. Looking into it.

**Comment by pierredelisle** [comment]
Should be fixed in PR #98.
