### ISSUE TITLE
the function of share device can not work

### ISSUE THREAD

**Issue by nicelyjust** [google-home/sample-app-for-matter-android#88]
after share device, another commissioner can not to commission the shared device

another commissioner's full log 
[commission_error.txt](https://github.com/google-home/sample-app-for-matter-android/files/10823582/commission_error.txt)

**Comment by pierredelisle** [comment]
I can help for issues related to GHSAFM, not so much with other commissioners.
If you provide phone logs where the sample app executes, we can verify that it does its job properly to initiate device sharing.

**Comment by nicelyjust** [comment]
opps ....the test device can't be set up which latest version

**Comment by nicelyjust** [comment]
Currently not being reproduce
