### ISSUE TITLE
How to connect to Thread Border Router using Google Home sample app?

### ISSUE THREAD

**Issue by palak-android** [google-home/sample-app-for-matter-android#95]
Hello,

I am trying to connect below Android application to Thread based matter device.
**Sample app for matter android source:** https://github.com/google-home/sample-app-for-matter-android/releases/tag/v1.3.0
**Sample app for matter android apk:** https://github.com/google-home/sample-app-for-matter-android/releases/download/v1.3.0/GHSAFM-1.3.0-default-debug.apk

I am facing the issue when I trying to connect Thread based matter device. Google sample application throwing the error as per below,

**"Your device requires a Thread border router"**

I have gone through https://openthread.io/guides/border-router/external-commissioning/android#thread_group_android_app. But application not available on Google play store.

Please guide for How connect Thread border router using Android application.

Thank you,
Palakkumar Suhagia,
Einfochips | Senior Engineer

**Comment by pierredelisle** [comment]
You need a device in your home network that is a Thread Border router.
See https://www.belkin.com/clp-thread-networking-2022-mesh-technology-for-smart-homes-and-devices.html.

Section "FULL LIST OF THREAD BORDER ROUTERS" lists the following:

- Apple TV 4K (2nd Gen or later)​
- Apple HomePod mini​
- Nanoleaf Lines​
- Nanoleaf Shapes​
- Nanoleaf Elements​
- eero 6​
- eero Pro 6​
- eero Pro​
- eero Beacon​
- Echo (4th Gen)​
- Nest Hub (2nd Gen)​
- Nest Hub Max​
- Nest Wifi

Updated April , 2022
